"""v6 indexes

Revision ID: c2c23206e0e1
Revises: 005
Create Date: 2026-05-11 19:42:04.157731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c23206e0e1'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_jobs_polling', 'jobs', ['status', 'run_at', 'next_retry_at', 'priority'], unique=False)
    op.create_index(op.f('ix_jobs_next_retry_at'), 'jobs', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_jobs_schedule_id'), 'jobs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_jobs_scheduled_for'), 'jobs', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_scheduled_for'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_schedule_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_next_retry_at'), table_name='jobs')
    op.drop_index('idx_jobs_polling', table_name='jobs')
    # ### end Alembic commands ###
